function r=PulseChannelInfo(varargin)
    % This function holds all the information that connect abstract pulse
    % to its hardware implementation 
    % each pulse is a structure in a cell array called inf
    % each stracture/Pulse MUST have the fields :
    %'ChannelName' and 'ChannelType'. In addition any number of 
    % fields can be added. 
    % !! all fields should be supported by CodeGenerator !!.
    % !! pulse of same type must have the same fields !!!
    % Channel type | fields 
    %---------------------------------
    %      'Dig'         'DigitalSwitch','OnIs'    
    %      'VCO'
    %      'DigitalSwitch','OnIs','SetFreqAddress','Freq2Value','SetAmpAddress'
    %      'PMT'         'Operation'
    %      'FifolessPMT' 'Operation','Threshold'
    %      'DDS'         'DDSNum','OnIs'
    %      'DDSwithSw'   'DDSNum','DigitalSwitch','OnIs'
    persistent info;
    if isempty(info)
        info={
        struct('ChannelName','OffRes422',...
               'ChannelType','Dig','DigitalSwitch',0,'OnIs',1),...         
        struct('ChannelName','OnRes422',...
               'ChannelType','VCO','DigitalSwitch',1,'OnIs',1,'SetFreqAddress',0,'Freq2Value','int16((freq-179.5)*0.1*3200)','SetAmpAddress',4),...
        struct('ChannelName','OnResCooling',...
               'ChannelType','VCO','DigitalSwitch',2,'OnIs',1,'SetFreqAddress',2,'Freq2Value','int16((freq-180.5)*0.1*3200)'),...
        struct('ChannelName','OpticalPumping',...
               'ChannelType','VCO','DigitalSwitch',3,'OnIs',1,'SetFreqAddress',2,'Freq2Value','int16((freq-180.5)*0.1*3200)'),...
        struct('ChannelName','Repump1092',...
               'ChannelType','VCO','DigitalSwitch',4,'OnIs',1,'SetFreqAddress',1,'Freq2Value','int16((freq-295)*0.074*3276)'),...
        struct('ChannelName','Repump1033',...
               'ChannelType','Dig','DigitalSwitch',5,'OnIs',1),...
        struct('ChannelName','674Channel2',...
               'ChannelType','Dig','DigitalSwitch',8,'OnIs',0),...
        struct('ChannelName','TACgate',...
               'ChannelType','Dig','DigitalSwitch',11,'OnIs',1),...
        struct('ChannelName','674Channel4',...
               'ChannelType','Dig','DigitalSwitch',6,'OnIs',0),...
        struct('ChannelName','674DDS1',...
               'ChannelType','DDS','DDSNum',1,'OnIs',100),...
        struct('ChannelName','674DDS1Switch',...
               'ChannelType','DDSwithSw','DDSNum',1,'DigitalSwitch',21,'OnIs',1),...
        struct('ChannelName','674PulseShaper',...
               'ChannelType','Dig','DigitalSwitch',8,'OnIs',1),...
        struct('ChannelName','RFDDS2',...
               'ChannelType','DDS','DDSNum',2,'OnIs',100),...
        struct('ChannelName','RFDDS2Switch',...
               'ChannelType','DDSwithSw','DDSNum',2,'DigitalSwitch',6,'OnIs',0),...
        struct('ChannelName','PhotonCount',...
               'ChannelType','PMT','Operation',0),...
        struct('ChannelName','PhotonCount1',...
               'ChannelType','PMT','Operation',1),...
        struct('ChannelName','PhotonCount2',...
               'ChannelType','PMT','Operation',2),...
        struct('ChannelName','PMTsAccumulate',...
               'ChannelType','FifolessPMT','Operation',4,'Threshold',-1),...
        struct('ChannelName','NoiseEater674',...
               'ChannelType','Dig','DigitalSwitch',26,'OnIs',0),...
        struct('ChannelName','Shutters',...
               'ChannelType','Dig','DigitalSwitch',14,'OnIs',0),...
        struct('ChannelName','DIO7',...
               'ChannelType','Dig','DigitalSwitch',15,'OnIs',0),...
        struct('ChannelName','DO8',...
               'ChannelType','Dig','DigitalSwitch',16,'OnIs',1),...
        struct('ChannelName','DO9',...
               'ChannelType','Dig','DigitalSwitch',9,'OnIs',1),...
        struct('ChannelName','DO10',...
               'ChannelType','Dig','DigitalSwitch',10,'OnIs',1),...
         struct('ChannelName','D11',...
               'ChannelType','Dig','DigitalSwitch',17,'OnIs',1),...
         struct('ChannelName','DO12',...
               'ChannelType','Dig','DigitalSwitch',26,'OnIs',1),...
         struct('ChannelName','DO13',...
               'ChannelType','Dig','DigitalSwitch',18,'OnIs',1),...
         struct('ChannelName','DO14',...
               'ChannelType','Dig','DigitalSwitch',19,'OnIs',1),...
         struct('ChannelName','CameraTrigger',...
               'ChannelType','Dig','DigitalSwitch',20,'OnIs',1),...
         struct('ChannelName','ExperimentTrigger',...
               'ChannelType','Dig','DigitalSwitch',7,'OnIs',1),...
         struct('ChannelName','674Switch2NovaTech',...
               'ChannelType','Dig','DigitalSwitch',22,'OnIs',1),...
         struct('ChannelName','NovaTechPort2',...
               'ChannelType','Dig','DigitalSwitch',24,'OnIs',1),...
         struct('ChannelName','DO20',...
               'ChannelType','Dig','DigitalSwitch',25,'OnIs',1)...
         };
%       the Fifoless state detection using Threshold is not availabe for this version 
%       struct('ChannelName','FifolessPhotonCount',...
%                'ChannelType','FifolessPMT','Operation',0,'Threshold',9),...

    end
    
    %--------------------------------------------------------
    if size(varargin,2)>0
        if isnumeric(varargin{1})
            r=info{varargin{1}}.(varargin{2});
        else
            numofchannel=size(info,2);
            num=1;
            while num<=numofchannel
                if strcmp(info{num}.ChannelName,varargin{1})
                    break;
                else
                    num=num+1;
                end    
            end
            if (num > numofchannel) 
                num=0;
                error('Channel name is not in ChannelInfo')
            end
            r=num;
        end
    else
       r=info;
    end
end